
["Resource Chickens"]
	#Allow resource chickens to breed.  0=no breeding, 1=all can breed, 2=set by individual configs.  Default: 2
	#Range: 0 ~ 2
	masterSwitchBreeding = 2
	#Allow resource chickens to cross breed.  false=Can only breed with same type.  Default: true
	allowCrossBreeding = true
	#Resource chickens require their drop item for food/breeding.  Default: false
	dropAsBreedingItem = false
	#% Chance that breeding with 'vanilla' chickens produce resource chickens. 0=Don't produce resource chickens.  Default: 80
	#Range: 0 ~ 100
	allowBreedingWithVanilla = 80
	#Allow conversion of 'vanilla' chickens to resource chickens.  Default: true
	allowConvertingVanilla = true
	#% Chance that resource is dropped upon death. 0=No resource dropped.  Default: 80
	#Range: 0 ~ 100
	allowDeathDropResource = 80
	#Allow chickens to drop resources naturally in world.  Default: false
	enableInWorldDrops = true

["Fake Player Interaction"]
	#Allow Fakeplayer/automation of resource chicken breeding.  Default: true
	allowFakeplayerBreeding = true
	#Allow Fakeplayer kills to produce loot drops.  Default: true
	allowFakeplayerLootDrops = true

["All Chickens"]
	#Allow shearing of chickens/ducks to get feathers.  Default: true
	allowShearingChickens = true
	#Chickens must be analyzed before breeding or laying drops.  Default: false  N/I
	analyseChickens = false

